# Generated by Django 4.2.16 on 2024-09-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='uuid',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
