# Generated by Django 4.2.16 on 2024-09-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_collectionmodel_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmodel',
            name='genres',
        ),
    ]
